#pragma once

namespace Engine
{
	namespace Pipeline
	{
		enum ENUM_PSO { PSO_DEFAULT, PSO_END };
	}

	enum RENDER_PRIORITY {RENDER_FIRST, RENDER_AFTER, RENDER_PRIORITY_END};
	enum RENDER_BLENDMODE { NOBLEND, BLEND, RENDER_BLENDMODE_END};
	enum RENDER_SHADERTYPE {SHADERTYPE_DEFAULT, SHADERTYPE_SIMPLE, RENDER_SHADERTYPE_END};
	enum RENDER_ROOTSIGTYPE {ROOTSIG_DEFAULT, RENDER_ROOTSIGTYPE_END};
}