#pragma once

namespace Engine
{
	namespace Pipeline
	{
		enum ENUM_PSO { PSO_DEFAULT, PSO_END };
	}

	enum RENDER_PRIORITY {RENDER_FIRST, RENDER_AFTER, RENDER_PRIORITY_END};
	enum RENDER_BLENDMODE { NOBLEND, BLEND, RENDER_BLENDMODE_END};
	enum RENDER_SHADERTYPE {SHADERTYPE_SIMPLE, SHADERTYPE_SIMPLE2, RENDER_SHADERTYPE_END};
	enum RENDER_PARAMCOMBO {PARAM_SIMPLE, PARAM_SAMPLER, RENDER_PARAMCOMBO_END}; // shader InputLayout Signiture

	enum ROOTSIG_TYPE { ROOTSIG_SIMLE, ROOTSIG_TEX, ROOTSIG_TEX_TRANSMAT, ROOTSIG_TYPE_END};
}